name: Testing Projects
on: workflow_dispatch
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Running Lint
        run: npm init @eslint/config
        run: npm run lint
      
  
