name: Testing Projects
on: workflow_dispatch
jobs:More actions
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    continue-on-error: true
    steps:
      - id: test-validate-id
        uses: actions/github-script@V6
        name: Add comment after validation
  notify-on-reject:
    runs-on: ubuntu-latest
    needs: ValidateProdDeployment
    if: needs.ValidateProdDeployment.result == 'failure' || needs.ValidateProdDeployment.result == 'cancelled'
    if: failure() || cancelled()
    steps:
      - name: Notify on rejects
      - run: echo 'Testing details'

    
          
  
