name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    continue-on-error: true
    steps:
      - id: test-validate-id
        uses: actions/github-script@V6
        name: Add comment after validation
  notify-on-reject:
    runs-on: ubuntu-latest
    needs: ValidateProdDeployment
    if: steps.test-validate-id.result == 'failure' || steps.test-validate-id.result == 'cancelled'
    steps:
      - name: Notify on rejects
        run: echo 'Testing details'

    
          
  
