name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    steps:
      - id: test-validate-id
        name: Add comment after validation
        run: |
            echo '${{github.job.status}}'
            
          
  
