name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    steps:
      - id: test-validate-id
        name: Add comment after validation
        uses: actions/github-script@V6
        with:
          #github-token: ${{secrets.GIT_PAT_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: 'vesambas',
              body: 'Deployment'
            })
            
          
  
