name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    outputs:
        results: ${{job.status}}
    steps:
      - id: test-validate-id
        name: Add comment after validation
  notify-on-reject:
    runs-on: ubuntu-latest
    needs: ValidateProdDeployment
    if: needs.ValidateProdDeployment.result == 'failure'
    steps:
      - name: Notify on rejects
        run: |
          echo 'Inside failure'
    
          
  
