name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    steps:
      - id: test-validate-id
        uses: actions/github-script@V6
        name: Add comment after validation
  notify-on-reject:
    runs-on: ubuntu-latest
    needs: ValidateProdDeployment
    if: failure()
    steps: 
      - name: Notify on rejects
        run: | 
          if [[ "${{ needs.ValidateProdDeployment.result }}" == "failure" ]]; then
            echo "rejected=true" >> $GITHUB_OUTPUT
          else
            echo "rejected=false" >> $GITHUB_OUTPUT
          fi
          echo "Inside Notify rejects"
          echo "After if"

    
          
  
