name: Testing Projects
on: workflow_dispatch
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      
  
