name: Testing Projects
on: workflow_dispatch
jobs:
  ValidateProdDeployment:
    runs-on: ubuntu-latest
    environment: Validate production deployment
    steps:
      - id: test-validate-id
        name: Add comment after validation
        if: ${{ github.job.status == 'cancelled'}}
        run: |
            echo "After clicking reject button"
            
          
  
